version: "3.7"

services:
  
  load:
    image: "csardelacal/commishes-reverse-proxy"
    networks:
      - http
    ports:
      - "mode=host,target=80,published=80"
      - "mode=host,target=443,published=443"
    deploy:
      mode: global
      constraints:
        - "node.labels.type == ingress"

networks:
  http:
    driver: overlay
    attachable: true