version: "3.7"

services:
  
  load:
    image: "reverse-proxy"
    volumes:
      - "./private.pem:/run/secrets/privkey:ro"
    networks:
      - http
    ports:
      - "80:80"
      - "443:443"

networks:
  http:
    external: true