name: Docker Image CI

on:
  schedule:
    - cron: '18 2 */16 * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - 
      name: Execute build script, retrieve the certificates
      run: |
        echo $CLOUDFLARE > credentials.txt
        sudo --preserve-env=EMAIL /bin/bash build.sh
        sudo chmod -R 0777 letsencrypt/
      env:
        EMAIL: "cesar@magic3w.com"
        CLOUDFLARE: ${{ secrets.CLOUDFLARE_AUTH }}
      
    # Create the docker image and push it to the registry
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: csardelacal/commishes-reverse-proxy:latest
